// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherActivityMatcher.Api.Data;

#nullable disable

namespace WeatherActivityMatcher.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateSlug")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.HourlyForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cloudcover")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precipitation")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature2m")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ValidTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Windspeed10m")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ValidTime")
                        .IsUnique();

                    b.ToTable("HourlyForecasts");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 52.369999999999997,
                            LocationName = "Amsterdam",
                            Longitude = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.WeatherConstraints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CloudMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("CloudMin")
                        .HasColumnType("REAL");

                    b.Property<int?>("DaysOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PrecipMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("TempMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("TempMin")
                        .HasColumnType("REAL");

                    b.Property<string>("TimeEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStart")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WindMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.ToTable("WeatherConstraints");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.Notification", b =>
                {
                    b.HasOne("WeatherActivityMatcher.Api.Models.Activity", "Activity")
                        .WithMany("Notifications")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.WeatherConstraints", b =>
                {
                    b.HasOne("WeatherActivityMatcher.Api.Models.Activity", "Activity")
                        .WithOne("Constraints")
                        .HasForeignKey("WeatherActivityMatcher.Api.Models.WeatherConstraints", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("WeatherActivityMatcher.Api.Models.Activity", b =>
                {
                    b.Navigation("Constraints");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
